[package]
name = "clock"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
debug = 0
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
gumdrop = "0.8.1"
jiff = "0.1.21"
thiserror = "2.0.11"
